title: Flow
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

collections:
  general-recommendations:
    permalink: "/:collection/:path"
    output: true

  country:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    general-recommendations:
      name: General Recommendations

    country:
      name: Country-Based Recommendations 
