title: Flow
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

collections:
  buying:
    permalink: /:path
    output: true
  country:
    permalink: /:path
    output: true

just_the_docs:
  collections:
    buying:
      name: General reccomendations
    country:
      name: Country-Based reccomendations 
